services:
  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: rabbitmq
    restart: unless-stopped
    ports:
      - "5672:5672"   # AMQP protocol
      - "15672:15672" # Management UI
    healthcheck:
      test: [ "CMD", "rabbitmq-diagnostics", "check_port_connectivity" ]
      interval: 5s
      timeout: 5s
      retries: 5

  aerotracker-api:
    image: ghcr.io/escalasebastian/aerotracker/aerotracker-api:latest
    container_name: aerotracker-api
    restart: unless-stopped
    ports:
      - "8080:8080"
    environment:
      - DB_URL=jdbc:postgresql://${DB_HOST}:${DB_PORT:-5432}/${DB_NAME:-aerotracker}
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
      - SPRING_RABBITMQ_HOST=rabbitmq
      - TELEGRAM_BOT_TOKEN=${TELEGRAM_BOT_TOKEN}
      - JAVA_TOOL_OPTIONS=-Xms128m -Xmx192m -XX:+UseSerialGC
    depends_on:
      rabbitmq:
        condition: service_healthy

  aerotracker-scheduler:
    image: ghcr.io/escalasebastian/aerotracker/aerotracker-scheduler:latest
    container_name: aerotracker-scheduler
    restart: unless-stopped
    environment:
      - DB_URL=jdbc:postgresql://${DB_HOST}:${DB_PORT:-5432}/${DB_NAME:-aerotracker}
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
      - SPRING_RABBITMQ_HOST=rabbitmq
      - JAVA_TOOL_OPTIONS=-Xms128m -Xmx192m -XX:+UseSerialGC
    depends_on:
      rabbitmq:
        condition: service_healthy

  aerotracker-price-checker:
    image: ghcr.io/escalasebastian/aerotracker/aerotracker-price-checker:latest
    container_name: aerotracker-price-checker
    restart: unless-stopped
    environment:
      - DB_URL=jdbc:postgresql://${DB_HOST}:${DB_PORT:-5432}/${DB_NAME:-aerotracker}
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
      - SPRING_RABBITMQ_HOST=rabbitmq
      - JAVA_TOOL_OPTIONS=-Xms128m -Xmx192m -XX:+UseSerialGC
    depends_on:
      rabbitmq:
        condition: service_healthy

  aerotracker-notification:
    image: ghcr.io/escalasebastian/aerotracker/aerotracker-notification:latest
    container_name: aerotracker-notification
    restart: unless-stopped
    environment:
      - DB_URL=jdbc:postgresql://${DB_HOST}:${DB_PORT:-5432}/${DB_NAME:-aerotracker}
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
      - SPRING_RABBITMQ_HOST=rabbitmq
      - TELEGRAM_BOT_TOKEN=${TELEGRAM_BOT_TOKEN}
      - JAVA_TOOL_OPTIONS=-Xms128m -Xmx192m -XX:+UseSerialGC
    depends_on:
      rabbitmq:
        condition: service_healthy

