spring:
  application:
    name: AeroTracker
  messages:
    basename: messages
    encoding: UTF-8
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/aerotracker}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
telegram:
  bot-token: ${TELEGRAM_BOT_TOKEN:mock-token-for-dev}